### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by kenberkeley** [joshuajaco/eslint-plugin-workspaces#19]
It seems currently we don't support [pnpm workspaces](https://pnpm.io/workspaces)...

I have raised an issue in https://github.com/azz/get-monorepo-packages/issues/10 as well.

**Comment by joshuajaco** [comment]
`get-monorepo-packages` has already been replaced with [find-workspaces](https://github.com/joshuajaco/find-workspaces) on main.
I've prereleased https://github.com/joshuajaco/eslint-plugin-workspaces/pull/21 in `eslint-plugin-workspaces@next`.
It will likely be a few days before I get to do some additional testing and update the docs for a full release.
Feel free to test it in the meantime and let me know how it works

**Comment by kenberkeley** [comment]
It works! Many thanks @joshuajaco !
