### ISSUE TITLE
Rule `workspaces/no-absolute-imports` is broken

### ISSUE THREAD

**Issue by stefanseeger** [joshuajaco/eslint-plugin-workspaces#22]
I'm having two files in the same error.
When I'm importing a export relatively your linter will complain

folder/Type.ts -> `export const something = "test";`

folder/Component.ts -> `import { something } from './Type';`
`Absolute imports within the current package are not allowedeslintworkspaces/no-absolute-imports`

This should be working, or am I misunderstanding something?

When I'm wrong, what else should this rule achieve?

**Comment by joshuajaco** [comment]
You are correct, the `no-absolute-imports` should not complain about the code you have shared. However from my testing it is working as intended.
Can you provide a reproduction of your issue? 
I need to know what version, what type of monorepo (yarn workspaces, lerna etc) and it's configuration you are using.

**Comment by joshuajaco** [comment]
Closing this as I'm unable to reproduce. Feel free to reopen with a reproduction if the issue persists.
